data_root: data
train_csv: train.csv
test_csv: test.csv
model:
  name: kneighbors
  args:
    n_neighbors: 4
checkpoint_path: models/knn_model.pkl
model_neural_network:
  name: neural_network  # Update with the name of your neural network model
  args:
    hidden_size: 256  # Example: Number of neurons in the hidden layer
    num_layers: 3